"""pipeline runs

Revision ID: 1a4ea49edd9e
Revises: 832d3649d98b
Create Date: 2026-07-26 11:18:22.026508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1a4ea49edd9e'
down_revision: Union[str, None] = '832d3649d98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scored_n', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summarized_n', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors_n', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index('ix_pipeline_runs_started_at', 'pipeline_runs', [sa.text('started_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_runs_started_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
