"""initial schema

Revision ID: 3200ee6cd13a
Revises: 
Create Date: 2026-07-26 04:08:25.599041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3200ee6cd13a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('last_polled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_success_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds')),
    sa.UniqueConstraint('url', name=op.f('uq_feeds_url'))
    )
    op.create_table('login_attempts',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_failure_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_login_attempts'))
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('profile_text', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_preferences_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences'))
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='user', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user','admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_username_lower', 'users', [sa.text('lower(username)')], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('feed_content', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('clean_title', sa.Text(), nullable=True),
    sa.Column('title_was_clickbait', sa.Boolean(), nullable=True),
    sa.Column('aside_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(clean_title,'') || ' ' || coalesce(summary,'') || ' ' || coalesce(full_text,''))", persisted=True), nullable=True),
    sa.CheckConstraint("status IN ('new','scored','hidden','summarized')", name=op.f('ck_articles_status_valid')),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_articles_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_articles_feed_guid')
    )
    op.create_index('ix_articles_created_at', 'articles', ['created_at'], unique=False)
    op.create_index('ix_articles_feed_id', 'articles', ['feed_id'], unique=False)
    op.create_index('ix_articles_score', 'articles', [sa.text('score DESC')], unique=False)
    op.create_index('ix_articles_search', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('seen_guids',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_seen_guids_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'guid', name=op.f('pk_seen_guids'))
    )
    op.create_table('user_article_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dismissed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.CheckConstraint("opinion IN ('liked','disliked')", name=op.f('ck_user_article_state_opinion_valid')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_user_article_state_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_article_state_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id', name=op.f('pk_user_article_state'))
    )
    op.create_index('ix_user_article_state_user_id', 'user_article_state', ['user_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('title_snapshot', sa.Text(), nullable=True),
    sa.Column('summary_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1,-1)', name=op.f('ck_votes_value_valid')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_votes_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes'))
    )
    op.create_index('ix_votes_article_id', 'votes', ['article_id'], unique=False)
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_user_id', table_name='votes')
    op.drop_index('ix_votes_article_id', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_user_article_state_user_id', table_name='user_article_state')
    op.drop_table('user_article_state')
    op.drop_table('seen_guids')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_search', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_score', table_name='articles')
    op.drop_index('ix_articles_feed_id', table_name='articles')
    op.drop_index('ix_articles_created_at', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('preferences')
    op.drop_table('login_attempts')
    op.drop_table('feeds')
    # ### end Alembic commands ###
