"""ollama call log

Revision ID: 7e07fa49fd95
Revises: 14c87b572311
Create Date: 2026-07-27 03:59:21.827734
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e07fa49fd95'
down_revision: Union[str, None] = '14c87b572311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ollama_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_preview', sa.Text(), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ollama_calls'))
    )
    op.create_index('ix_ollama_calls_at', 'ollama_calls', [sa.text('at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ollama_calls_at', table_name='ollama_calls')
    op.drop_table('ollama_calls')
    # ### end Alembic commands ###
