"""topics and rules

Revision ID: 832d3649d98b
Revises: 3200ee6cd13a
Create Date: 2026-07-26 10:51:54.301955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '832d3649d98b'
down_revision: Union[str, None] = '3200ee6cd13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_rules',
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('adjustment', sa.Float(), server_default='0', nullable=False),
    sa.Column('muted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('topic', name=op.f('pk_topic_rules'))
    )
    op.add_column('articles', sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('articles', sa.Column('cluster_id', sa.Text(), nullable=True))
    op.create_index('ix_articles_cluster_id', 'articles', ['cluster_id'], unique=False)
    op.create_index('ix_articles_topics', 'articles', ['topics'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_topics', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_cluster_id', table_name='articles')
    op.drop_column('articles', 'cluster_id')
    op.drop_column('articles', 'topics')
    op.drop_table('topic_rules')
    # ### end Alembic commands ###
