"""extract source

Revision ID: ab6a87caa616
Revises: 1a4ea49edd9e
Create Date: 2026-07-26 12:09:03.804635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab6a87caa616'
down_revision: Union[str, None] = '1a4ea49edd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('extract_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'extract_source')
    # ### end Alembic commands ###
